version: '3'
services:
  db:
    image: postgres:11
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "51000:5432"
    environment:
      POSTGRES_DB: rails_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
  db_test:
    image: postgres:11
    volumes:
      - ./db_test:/var/lib/postgresql/data
    ports:
      - "51001:5432"
    environment:
      POSTGRES_DB: rails_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
  web:
    build: ./
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
    ports:
      - "51002:3000"
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
      - db_test
